parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: social_base
    database_user: root
    database_password: root
    mailer_transport: gmail
    mailer_host: 
    mailer_user: 2sn.supteam@gmail.com
    mailer_password: etnateam
    locale: en
    secret: d06e08d56e80ed257c6baa4cec54f9334bd5ebe7
    database_path: null
