parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: social_base
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: d06e08d56e80ed257c6baa4cec54f9334bd5ebe7
    database_path: null
