etna_social_home:
    pattern:  /home
    defaults: { _controller: EtnaSocialBundle:Home:index }

etna_social_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EtnaSocialBundle:Default:index }

etna_social_ajout_user:
    pattern: /register
    defaults: { _controller: EtnaSocialBundle:Regist:register }

etna_social_login:
    pattern: /login
    defaults: { _controller: EtnaSocialBundle:Security:login }

etna_social_forgot_password:
    pattern: /forgot
    defaults: { _controller: EtnaSocialBundle:Default:forgot }

etna_social_oubli:
    pattern: /oubli
    defaults: { _controller: EtnaSocialBundle:Forgot:request}

etna_social_oubli_send_email:
    pattern: /send-email
    defaults: { _controller: EtnaSocialBundle:Forgot:sendEmail}

etna_social_oubli_check_email:
    pattern: /check-email
    defaults: { _controller: EtnaSocialBundle:Forgot:checkEmail}

etna_social_resetting_reset:
    pattern: /resetting/reset/{token}
    defaults: { _controller: EtnaSocialBundle:Forgot:reset}

etna_social_profile:
    pattern:  /{username}
    defaults: { _controller: EtnaSocialBundle:Profile:index }

etna_social_status:
    pattern:  /statut/
    defaults: { _controller: EtnaSocialBundle:Statut:new }

etna_social_remove_status:
    pattern:  /statut/remove/
    defaults: { _controller: EtnaSocialBundle:Statut:remove }

etna_social_get_friend:
    pattern: /{username}/friends
    defaults: { _controller: EtnaSocialBundle:Friend:getfriend }

etna_social_find_friend:
    pattern: /{username}/find_friends
    defaults: { _controller: EtnaSocialBundle:Friend:findfriend }

etna_social_remove_friend:
    pattern: /{username}/remove_friends/{username_friend}
    defaults: { _controller: EtnaSocialBundle:Friend:removefriend }

etna_social_add_friend:
    pattern: /{username}/add_friends/{username_friend}
    defaults: { _controller: EtnaSocialBundle:Friend:addfriend }

etna_social_com_status:
    pattern:  /statut/com
    defaults: { _controller: EtnaSocialBundle:ComStatut:new }

etna_social_remove_com_status:
    pattern:  /statut/remove/com
    defaults: { _controller: EtnaSocialBundle:ComStatut:remove }

etna_social_get_albums:
    pattern: /{username}/albums
    defaults: { _controller: EtnaSocialBundle:Album:getAlbum }

etna_social_add_album:
    pattern: /{username}/add_album
    defaults: { _controller: EtnaSocialBundle:Album:addAlbum }

etna_social_remove_album:
    pattern: /{username}/albums/{albumname}/remove_album
    defaults: { _controller: EtnaSocialBundle:Album:removeAlbum }

etna_social_get_photos:
    pattern: /{username}/albums/{albumname}
    defaults: { _controller: EtnaSocialBundle:Photo:getPhotos }

etna_social_add_photo:
    pattern: /{username}/albums/{albumname}/add_photo
    defaults: { _controller: EtnaSocialBundle:Photo:addPhoto }

etna_social_display_photo:
    pattern: /{username}/albums/{albumname}/{photoid}
    defaults: { _controller: EtnaSocialBundle:Photo:displayPhoto }

etna_social_remove_photo:
    pattern: /{username}/albums/{albumname}/{photoid}/remove_photo
    defaults: { _controller: EtnaSocialBundle:Photo:removePhoto }

etna_social_change_photo:
    pattern: /{username}/profile_picture
    defaults: { _controller: EtnaSocialBundle:Photo:changeProfilePhoto }

etna_social_set_photo:
    pattern: /{username}/albums/{albumname}/{photoid}/set_photo
    defaults: { _controller: EtnaSocialBundle:Photo:setProfilePhoto }

etna_social_profil_modif:
    pattern: /{username}/modifier
    defaults: { _controller: EtnaSocialBundle:Modifcompte:edit}

etna_social_profil_mdp:
    pattern: /{username}/change-password
    defaults: { _controller: EtnaSocialBundle:Changepass:changePassword}