etna_social_home:
    pattern:  /home
    defaults: { _controller: EtnaSocialBundle:Home:index }

etna_social_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EtnaSocialBundle:Default:index }

etna_social_ajout_user:
    pattern: /register
    defaults: { _controller: EtnaSocialBundle:Regist:register }

etna_social_login:
    pattern: /login
    defaults: { _controller: EtnaSocialBundle:Security:login }

etna_social_forgot_password:
    pattern: /forgot
    defaults: { _controller: EtnaSocialBundle:Default:forgot }

etna_social_profile:
    pattern:  /{username}
    defaults: { _controller: EtnaSocialBundle:Profile:index }

etna_social_statut:
    pattern:  /login_check
    defaults: { _controller: EtnaSocialBundle:Statut:new }

