etna_social_home:
    pattern:  /home
    defaults: { _controller: EtnaSocialBundle:Default:index }

etna_social_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EtnaSocialBundle:Default:index }

etna_social_ajout_user:
    pattern: /register
    defaults: { _controller: EtnaSocialBundle:Default:ajouter }

etna_social_login:
    pattern: /login
    defaults: { _controller: EtnaSocialBundle:Security:login }